defmodule ProjectEuler.Two do
  @moduledoc """
  Even Fibonacci numbers
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  https://projecteuler.net/problem=2
  """

  def run do
    solve(1, 2, 0)
  end

  defp solve(_a, b, sum) when b >= 4_000_000 do
    IO.puts(sum)
  end

  defp solve(a, b, sum) when rem(b, 2) === 0 do
    c = a + b
    sum = sum + b
    solve(b, c, sum)
  end

  defp solve(a, b, sum) do
    c = a + b
    solve(b, c, sum)
  end
end

# The answer is: 4613732.
